insert into admin(aseq, id, pw) values(admin_seq.nextval, 'admin', 'admin');
insert into member(useq, id, pw, name, phone, gender) values(member_seq.nextval, 'selectjuno@gmail.com', '1234', 'juno', '010-2172-7798', 'M');
insert into theme(tseq, theme) values(theme_seq.nextval, 'FLO 차트');
insert into theme(tseq, theme) values(theme_seq.nextval, '지금 급상승 중');
insert into theme(tseq, theme) values(theme_seq.nextval, '해외 소셜 차트');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 발라드');
insert into theme(tseq, theme) values(theme_seq.nextval, '해외 팝');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 댄스/일렉');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 알앤비');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 힙합');
insert into theme(tseq, theme) values(theme_seq.nextval, '트로트');
insert into theme(tseq, theme) values(theme_seq.nextval, '해외 알앤비');
insert into theme(tseq, theme) values(theme_seq.nextval, '해외 힙합');
insert into theme(tseq, theme) values(theme_seq.nextval, 'OST/BGM');
insert into theme(tseq, theme) values(theme_seq.nextval, '키즈');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 인디');
insert into theme(tseq, theme) values(theme_seq.nextval, '클래식');
insert into theme(tseq, theme) values(theme_seq.nextval, '뉴에이지');
insert into theme(tseq, theme) values(theme_seq.nextval, '국내 팝/어쿠스틱');
insert into theme(tseq, theme) values(theme_seq.nextval, '해외 일렉트로닉');
insert into theme(tseq, theme) values(theme_seq.nextval, 'CCM');
insert into theme(tseq, theme) values(theme_seq.nextval, '시원한');
insert into theme(tseq, theme) values(theme_seq.nextval, '감성적인');
insert into theme(tseq, theme) values(theme_seq.nextval, '슬픈');
insert into theme(tseq, theme) values(theme_seq.nextval, '기쁜');
insert into genre(gseq, genre) values(genre_seq.nextval, '댄스');
insert into genre(gseq, genre) values(genre_seq.nextval, '발라드');
insert into artist(atseq, name, groupyn, gender, gseq, img, description) values(artist_seq.nextval, 'Ed Sheeran', 'N', 'M', 1, null, '아티스트 소개');
insert into artist_like(useq, atseq) values(1, 1);
insert into album(abseq, atseq, title, img, content) values(album_seq.nextval, 1, 'First Album', null, '앨범소개');
insert into album_like(useq, abseq) values(1, 1);
insert into music(mseq, abseq, atseq, gseq, title, content, theme, titleyn) values(music_seq.nextval, 1, 1, 1, 'Lego House', '엄청난 첫번째노래 정보', '1|4|5|6|7|9', 'Y');
insert into music(mseq, abseq, atseq, gseq, title, content, theme, titleyn) values(music_seq.nextval, 1, 1, 1, 'One', '엄청난 두번째노래 정보', '2|3|5|6|7|9', 'N');
insert into music_like(mseq, useq) values(1, 1);
-- insert into music_ban(mseq, useq) values(1, 1);
insert into music_reply(rseq, mseq, useq, content) values(music_reply_seq.nextval, 1, 1, '개조아여');
insert into music_reply(rseq, mseq, useq, content) values(music_reply_seq.nextval, 2, 1, '역시... 뒤집어 놓으다.. 음정, 박자.. 와...');
insert into bundle_master(bmseq, useq, title, useyn) values (bundle_master_seq.nextval, 0, '그리움 가득한 밤 문득 생각나는 발라드', 'Y');
insert into bundle_master(bmseq, useq, title, useyn) values (bundle_master_seq.nextval, 1, '알람 대신 상쾌함 가득한 이 노래', 'Y');
insert into bundle_master(bmseq, useq, title, useyn) values (bundle_master_seq.nextval, 2, '에너지 가득 귀에 꽂는 비타민 송', 'Y');
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 1, 1);
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 1, 2);
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 2, 1);
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 2, 2);
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 3, 1);
insert into bundle_detail(bdseq, bmseq, mseq) values (bundle_detail_seq.nextval, 3, 2);
insert into taste(taste_seq, useq, atseq, tseq, gseq) values (taste_seq.nextval, 1, 1,  null, null);
insert into taste(taste_seq, useq, atseq, tseq, gseq) values (taste_seq.nextval, 1, null, 1, null);
insert into taste(taste_seq, useq, atseq, tseq, gseq) values (taste_seq.nextval, 1, null, null, 1);
insert into qna(qseq, useq, title, content) values(qna_seq.nextval, 1, '블루투스 연결은 어떻게 하나요?', '안녕하세요. 해당 웹을 10년간 이용해온 사용자인데요. 혹시 블루투스 연결은 안되나요?');
insert into qReply(qrseq, qseq, aseq, content) values(qReply_seq.nextval, 1, 1, '컴퓨터에 블루투스 장치가 연결되었는지 확인하여주시고, 연결되었음에도 들리지않는다면 해당 장치의 문제이므로 저희사이트와는 무관한 증상입니다.');
insert into notice(nseq, title, content) values(notice_seq.nextval, 'title', 'content');